
LycheeRecipeManager.addRecipe("spider", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:spider_eye>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:spider", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons an eight eyed creature")
);
LycheeRecipeManager.addRecipe("zomb", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:rotten_flesh>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:zombie", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons an undead to walk the earth")
);
LycheeRecipeManager.addRecipe("skell", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:bone>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:skeleton", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons an unholy amalgam of bones")
);
LycheeRecipeManager.addRecipe("cavesp", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:tconstruct:venom_bottle>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:cave_spider", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true),LycheePosts.dropItem(<item:minecraft:glass_bottle>)])
    .comment("Summons a venomous arachnid")
);
LycheeRecipeManager.addRecipe("gaurd", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:prismarine_shard>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:gaurdian", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a gaurdian of submerged temples")
);
LycheeRecipeManager.addRecipe("pillage", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:emerald>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:pillager", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a raider of villages")
);
LycheeRecipeManager.addRecipe("slimesumm", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:slime_ball>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:slime", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a bouncy creature")
);
LycheeRecipeManager.addRecipe("magslime", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:magma_cream>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:magma_slime", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a hellish bouncy creature")
);
LycheeRecipeManager.addRecipe("creeper", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:gunpowder>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:creeper", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~ ~", true)])
    .comment("Summons a very explosive stalker")
);
LycheeRecipeManager.addRecipe("ghast", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:ghast_tear>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:ghast ~ ~5 ~", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a ghastly floating visage")
);
LycheeRecipeManager.addRecipe("blaze", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:blaze_powder>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:blaze", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a firey demon")
);
LycheeRecipeManager.addRecipe("withers", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:tconstruct:necrotic_bone>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:wither_skeleton", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a scorched amalgam of bones")
);
LycheeRecipeManager.addRecipe("vindic", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:iron_axe>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:vindicator", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons an axe wielding mansion denizen")
);
LycheeRecipeManager.addRecipe("phant", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:phantom_membrane>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:phantom ~ ~3 ~", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~ ~", true)])
    .comment("Summons a nightmare")
);
LycheeRecipeManager.addRecipe("husk", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:rotten_flesh>,<item:minecraft:sand>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:husk", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a dried out zombie")
);
LycheeRecipeManager.addRecipe("stray", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:bone>,<item:minecraft:snow>, <item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:stray", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a frozen amalgam of bones")
);
LycheeRecipeManager.addRecipe("ender", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:ender_pearl>,<item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:enderman", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true),LycheePosts.dropItem(<item:minecraft:ender_pearl>)])
    .comment("Summons a teleporting creature from places beyond")
);
LycheeRecipeManager.addRecipe("pigl", <recipetype:lychee:item_inside>, new LycheeRecipeBuilder()
    .itemIn([<item:minecraft:cracked_polished_blackstone_bricks>,<item:minecraft:golden_helmet>.anyDamage(),<item:botania:mana_powder>])
    .blockIn(<block:tconstruct:blood_fluid>)
    .post([LycheePosts.placeBlock(<block:minecraft:air>),LycheePosts.executeCommand("summon minecraft:piglin", true),LycheePosts.executeCommand("summon minecraft:lightning_bolt ~ ~2 ~", true)])
    .comment("Summons a gold hungry pig-man from hell")
);
